version: "2"
services:
  message-center:
    image: registry.dx.io/dx-pilot/message-center:master-f658d1e
    container_name: message-center
    restart: always
    ports:
    - '8888:8888'
    environment:
      HOST: 10.10.30.59
      Port: 3303
      USER: root
      PASSWORD: 123456
      DB: message_center

